title: Kevin's learning page
author: kcexn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Test Test
# social links
twitter_username: your-twitter-handle
github_username:  kcexn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
